version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./../pkg/db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    tty: true
    container_name: payroll-api
    build:
      context: ./..
      dockerfile: Dockerfile
      target: dev
      args:
        TARGETOS: linux
        TARGETARCH: amd64
        VERSION: v0.1
        BINARY_NAME: payroll
    image: payroll
    ports:
      - 8088:8088
    depends_on:
      - db
    links:
      - db
    restart: always
    volumes:
      - './:/pkg'
volumes:
  db:
    driver: local